const productData = [
    {
      id: 1,
      name: "Strawberry",
      image: "/assets/images/strawberry.jpg",
      originalPrice: 91.78,
      discountedPrice: 72.5,
      discount: 21,
      weight: "200 g",
      category: "Exotic Fruits",
      rating: 4,
      brand: "Ambrosia",
    },
    {
      id: 2,
      name: "Mangosteen",
      image: "/assets/images/mangosteen.jpg",
      originalPrice: 479.45,
      discountedPrice: 364.38,
      discount: 24,
      weight: "2 pcs",
      category: "Exotic Fruits",
      rating: 2,
      brand: "Amul",
    },
    {
      id: 3,
      name: "Broccoli",
      image: "/assets/images/broccoli.jpg",
      originalPrice: 141,
      discountedPrice: 24,
      discount: 42,
      weight: "1 pc (Approx. 250g-500g)",
      category: "Exotic Vegetables",
      rating: 2,
      brand: "Dinshaw",
    },
    {
      id: 4,
      name: "Dragon Fruit",
      image: "/assets/images/dragon-fruit.jpg",
      originalPrice: 199.50,
      discountedPrice: 159.60,
      discount: 20,
      weight: "1 pc (Approx. 350g-400g)",
      category: "Exotic Fruits",
      rating: 5,
      brand: "Fresh Harvest",
    },
    {
      id: 5,
      name: "Avocado",
      image: "/assets/images/avocado.jpg",
      originalPrice: 125.00,
      discountedPrice: 99.00,
      discount: 21,
      weight: "1 pc",
      category: "Exotic Fruits",
      rating: 4,
      brand: "Green Valley",
    },
    {
      id: 6,
      name: "Kiwi",
      image: "/assets/images/kiwi.jpg",
      originalPrice: 85.00,
      discountedPrice: 68.00,
      discount: 20,
      weight: "3 pcs",
      category: "Exotic Fruits",
      rating: 3,
      brand: "Ambrosia",
    },
    {
      id: 7,
      name: "Asparagus",
      image: "/assets/images/asparagus.jpg",
      originalPrice: 249.00,
      discountedPrice: 199.20,
      discount: 20,
      weight: "200g bundle",
      category: "Exotic Vegetables",
      rating: 5,
      brand: "Green Valley",
    },
    {
      id: 8,
      name: "Red Bell Pepper",
      image: "/assets/images/red-bell-pepper.jpg",
      originalPrice: 90.00,
      discountedPrice: 72.00,
      discount: 20,
      weight: "1 pc (Approx. 150g-200g)",
      category: "Exotic Vegetables",
      rating: 4,
      brand: "Fresh Harvest",
    },
    {
      id: 9,
      name: "Blueberry",
      image: "/assets/images/blueberry.jpg",
      originalPrice: 299.00,
      discountedPrice: 239.20,
      discount: 20,
      weight: "125g pack",
      category: "Exotic Fruits",
      rating: 5,
      brand: "Ambrosia",
    },
    {
      id: 10,
      name: "Zucchini",
      image: "/assets/images/zucchini.jpg",
      originalPrice: 60.00,
      discountedPrice: 48.00,
      discount: 20,
      weight: "1 pc (Approx. 250g-300g)",
      category: "Exotic Vegetables",
      rating: 3,
      brand: "Green Valley",
    },
    {
      id: 11,
      name: "Raspberry",
      image: "/assets/images/raspberry.jpg",
      originalPrice: 349.00,
      discountedPrice: 279.20,
      discount: 20,
      weight: "125g pack",
      category: "Exotic Fruits",
      rating: 4,
      brand: "Fresh Harvest",
    },
    {
      id: 12,
      name: "Baby Corn",
      image: "/assets/images/carrot.jpg",
      originalPrice: 80.00,
      discountedPrice: 68.00,
      discount: 15,
      weight: "200g pack",
      category: "Exotic Vegetables",
      rating: 3,
      brand: "Amul",
    },
    {
      id: 13,
      name: "Passion Fruit",
      image: "/assets/images/carrot.jpg",
      originalPrice: 189.00,
      discountedPrice: 151.20,
      discount: 20,
      weight: "3 pcs",
      category: "Exotic Fruits",
      rating: 4,
      brand: "Ambrosia",
    },
    {
      id: 14,
      name: "Cherry Tomatoes",
      image: "/assets/images/tomato.jpg",
      originalPrice: 70.00,
      discountedPrice: 56.00,
      discount: 20,
      weight: "200g pack",
      category: "Exotic Vegetables",
      rating: 4,
      brand: "Fresh Harvest",
    },
    {
      id: 15,
      name: "Golden Kiwi",
      image: "/assets/images/mango.jpg",
      originalPrice: 120.00,
      discountedPrice: 96.00,
      discount: 20,
      weight: "3 pcs",
      category: "Exotic Fruits",
      rating: 5,
      brand: "Ambrosia",
    },
    {
      id: 16,
      name: "Artichoke",
      image: "/assets/images/tomato.jpg",
      originalPrice: 220.00,
      discountedPrice: 187.00,
      discount: 15,
      weight: "1 pc",
      category: "Exotic Vegetables",
      rating: 3,
      brand: "Green Valley",
    },
    {
      id: 17,
      name: "Papaya",
      image: "/assets/images/papaya.jpg",
      originalPrice: 95.00,
      discountedPrice: 76.00,
      discount: 20,
      weight: "1 pc (Approx. 800g-1kg)",
      category: "Exotic Fruits",
      rating: 3,
      brand: "Fresh Harvest",
    },
    {
      id: 18,
      name: "Purple Cabbage",
      image: "/assets/images/spinach.jpg",
      originalPrice: 80.00,
      discountedPrice: 60.00,
      discount: 25,
      weight: "1 pc (Approx. 500g-700g)",
      category: "Exotic Vegetables",
      rating: 4,
      brand: "Dinshaw",
    },
    {
      id: 19,
      name: "Rambutan",
      image: "/assets/images/papaya.jpg",
      originalPrice: 499.00,
      discountedPrice: 399.20,
      discount: 20,
      weight: "250g pack",
      category: "Exotic Fruits",
      rating: 4,
      brand: "Ambrosia",
    },
    {
      id: 20,
      name: "Fennel Bulb",
      image: "/assets/images/orange.jpg",
      originalPrice: 120.00,
      discountedPrice: 96.00,
      discount: 20,
      weight: "1 pc (Approx. 200g-250g)",
      category: "Exotic Vegetables",
      rating: 3,
      brand: "Green Valley",
    },
    {
      id: 21,
      name: "Star Fruit",
      image: "/assets/images/mango.jpg",
      originalPrice: 150.00,
      discountedPrice: 120.00,
      discount: 20,
      weight: "2 pcs",
      category: "Exotic Fruits",
      rating: 3,
      brand: "Fresh Harvest",
    },
    {
      id: 22,
      name: "Bok Choy",
      image: "/assets/images/avocado.jpg",
      originalPrice: 90.00,
      discountedPrice: 72.00,
      discount: 20,
      weight: "250g pack",
      category: "Exotic Vegetables",
      rating: 4,
      brand: "Amul",
    },
    {
      id: 23,
      name: "Kale",
      image: "/assets/images/avocado.jpg",
      originalPrice: 110.00,
      discountedPrice: 88.00,
      discount: 20,
      weight: "200g pack",
      category: "Exotic Vegetables",
      rating: 4,
      brand: "Green Valley",
    },
    {
      id: 24,
      name: "Pomelo",
      image: "/assets/images/apple.jpg",
      originalPrice: 220.00,
      discountedPrice: 176.00,
      discount: 20,
      weight: "1 pc (Approx. 1.2kg-1.5kg)",
      category: "Exotic Fruits",
      rating: 3,
      brand: "Ambrosia",
    },
    {
      id: 25,
      name: "Organic Apple",
      image: "/assets/images/apple.jpg",
      originalPrice: 150.00,
      discountedPrice: 127.50,
      discount: 15,
      weight: "4 pcs pack",
      category: "Organic Fruits",
      rating: 5,
      brand: "Organic Harvest",
    },
    {
      id: 26,
      name: "Organic Spinach",
      image: "/assets/images/organic-spinach.jpg",
      originalPrice: 80.00,
      discountedPrice: 64.00,
      discount: 20,
      weight: "200g pack",
      category: "Organic Vegetables",
      rating: 5,
      brand: "Organic Harvest",
    },
    {
      id: 27,
      name: "Organic Tomato",
      image: "/assets/images/organic-tomato.jpg",
      originalPrice: 70.00,
      discountedPrice: 59.50,
      discount: 15,
      weight: "500g pack",
      category: "Organic Vegetables",
      rating: 4,
      brand: "Organic Harvest",
    },
    {
      id: 28,
      name: "Organic Banana",
      image: "/assets/images/organic-banana.jpg",
      originalPrice: 90.00,
      discountedPrice: 76.50,
      discount: 15,
      weight: "6 pcs (Approx. 800g-1kg)",
      category: "Organic Fruits",
      rating: 4,
      brand: "Pure & Sure",
    },
    {
      id: 29,
      name: "Organic Carrot",
      image: "/assets/images/organic-carrot.jpg",
      originalPrice: 65.00,
      discountedPrice: 52.00,
      discount: 20,
      weight: "500g pack",
      category: "Organic Vegetables",
      rating: 4,
      brand: "Pure & Sure",
    },
    {
      id: 30,
      name: "Organic Mango",
      image: "/assets/images/mango.jpg",
      originalPrice: 230.00,
      discountedPrice: 195.50,
      discount: 15,
      weight: "2 pcs (Approx. 600g-700g)",
      category: "Organic Fruits",
      rating: 5,
      brand: "Organic Harvest",
    }
  ];

  export default productData;